#!/usr/bin/python3

import argparse
import csv
import sys
from enwiktionary_wordlist.wordlist import Wordlist
from enwiktionary_wordlist.all_forms import AllForms

if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser(description="Generate forms-to-lemmas data from wordlist")
    parser.add_argument("wordlist", help="wordlist")
    parser.add_argument("--low-mem", help="Use less memory", action='store_true', default=False)
    args = parser.parse_args()

    cache_words = not args.low_mem

    with open(args.wordlist) as wordlist_data:
        wordlist = Wordlist(wordlist_data, cache_words=cache_words)

        allforms = AllForms.from_wordlist(wordlist)
        for line in allforms.all_csv:
            print(line)
